wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.20
    code_path: code/partB/main.py
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.3
    t:
      1:
      - 2
      - 3
      - 5
      2:
      - 2
      - 3
      - 5
      4: 3.6.3
      5: 0.10.20
      8:
      - 3
      - 5
